### PR TITLE
Add push notification consent banner

### PR DESCRIPTION
**Pull request by sinaru**
### Description
A new banner for push notifications is displayed. It should contain following links. 
- Enable: To allow push notifications
- hide: hides the banner. Never shown again for 365 days. 
- Learn more: User is navigated to a page containing what is push notifications and how it will be used. 
- Should only be displayed for logged in users. 
- Introduce "Never show"  link. 
- ~"Hide" and "Never show" should be cross session based (multiple browsers) for the user.~

Following is a preview of the banner:
image

### CODE REVIEW

**Comment by sinaru** [comment]
@edwardrb on the second thought, let's only set the selection for the user in the browser and not remember across different browsers. We can re-evaluate the approach if it becomes annoying to the user. Therefore the following is not implemented in this card:
> "Hide" and "Never show" should be cross session based (multiple browsers) for the user.

**Comment by edwardrb** [comment]
@sinaru conflicts?

**Comment by sinaru** [comment]
@edwardrb Merging to master as per your input on passing QA.

**Comment by edwardrb** [comment]
Thanks!

**Pull request merged**
